### ISSUE TITLE
CpuTopologySync.kext is no longer needed now

### ISSUE THREAD

**Issue by hjames1** [bestplay9384/EFI-GIGABYTE-Z690-Gaming-X-DDR4-12700K-RX5700XT-Hackintosh#1]
Hi, CpuTopologySync is now a quirk of OpenCore starting from version 0.7.7 (set ProvideCurrentCpuInfo to True instead), so CpuTopologySync.kext is no longer needed.

**Comment by bestplay9384** [comment]
I will check it and eventually fix :)

Ad: Done, fixed in last commit, closing.
