### ISSUE TITLE
Boot loops

### ISSUE THREAD

**Issue by LavenderMP** [bestplay9384/EFI-GIGABYTE-Z690-Gaming-X-DDR4-12700K-RX5700XT-Hackintosh#3]
I was able to boot it in the Install step but it keep reboot after I enter the disk

**Comment by bestplay9384** [comment]
Remember to enable USBInjectAll.kext but disable my Z690UsbMap kext, every one needs to map USB ports themselves. 
This it to less info to determine what is going wrong on boot, but for me it was USB ports before mapping i made + also remember to Boot from Pendrive (USB Installer) - you have to assign correct EFI manually

**Comment by LavenderMP** [comment]
Thanks man!!
