### ISSUE TITLE
NEED YOUR HELP PLEASE !!!

### ISSUE THREAD

**Issue by sandrvoxon** [bestplay9384/EFI-GIGABYTE-Z690-Gaming-X-DDR4-12700K-RX5700XT-Hackintosh#6]
Hi ! First of all thank you so much for you work. I've got exactly the same specs except GPU. My GPU is 6800 xt and i cant get a right soft powerplay table to make fans spin at idle. Can you help me to guide how to make fans spin at idle ? Thanks.

**Comment by bestplay9384** [comment]
@sandrvoxon 

I dont have this GPU and didn't have any chance to try it out. I can only send you to official dortania guide for AMD GPUs [here](https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#navi-21-series).
Please refer also to [tonymacx86.com](https://www.tonymacx86.com/) forum, where you should find others with same GPU and probably same issues :)
