### ISSUE TITLE
just a couple of short questions...

### ISSUE THREAD

**Issue by tequilahut** [bestplay9384/EFI-GIGABYTE-Z690-Gaming-X-DDR4-12700K-RX5700XT-Hackintosh#8]
First of all! thank you for the files thank you for the effort! 

I rebuild the machine. its working all good.

My questions are the following: 

- Settings > IOPorts > SATA Configuration > SATA Mode = AHCI -- I Don't find that in the configuration (sata) - I think I doesent matter because I made it working - I guess it does not matter right?
- Performance Results: my PR are a lot higher -- 2261 Single-Core Score  but  multicore is a lot less 10891 // Multi-Core Score and I don't know why. even with OC: (2439 Single-Core Score 11648Multi-Core Score) - I cannot reach your MCSs :(
- Last but not least i am curious if you overclocked your RAM? Mine is running right at 3.6 GHZ with xmp1 and that's it: XMP Profile 1 - 3.6 GHz enabled, up to 5.2 GHz in macOS-- where do you see the 5.2 ghz?

**Comment by bestplay9384** [comment]
Hi @tequilahut 

1. SATA AHCI - if you can't find it in UEFI configuration, it is probably the only option (it is nowadays kind of typical choice). If you have exactly the same motherboard, look if Your BIOS version is the same as mine - as far as i remember it is the one referred in Readme (F8b), but if your motherboard is different - there is no way i can help to find the option ;) Look up for some motherboard company docs or sth... (or use the docs book you got with the mobo in the box)
2. The attached Performance Results are the best i  had occasion to perform. I tried multiple times with multiple PlatformInfo values (tried MacPro7,1 and some more). What is more i made it as i remembered in previous Mac OS, all those params differs the results. In Sonoma i did not have any chance to get the same or better results unfortunately. I don't have any advice beside trying and trying with different performance configurations :D Remember there is also possibility that results will get worse if you have apps running (especially in background, these you cannot see at first glance).
3. Nah, i did not overclock anything. I use XMP1 Profile. I don't remember exactly but i read som article where they were trying to overclock it, however as i say - i did not try to touch any OC stuff :)
